### ISSUE TITLE
Overzealous File Identification

### ISSUE THREAD

**Issue by jtgans** [tsalvo/Z80-Nova-Extension#1]
For some bizarre reason, shell scripts end up identified as Z80 source. Seems a bit overzealous?

**Comment by jtgans** [comment]
Same issue occurs with 6502 as well. Weird.

**Comment by tsalvo** [comment]
<detectors>
        <extension priority="1.0">s,S,asm,</extension>
    </detectors>

Are you using extension .s for shell scripts? I don't think .sh files would be matched, but I'll have to try this out as soon as I get a chance. Otherwise I suspect it's the trailing comma here. Maybe some files are getting matched beyond what's in that list?There's no place where I'm actually trying to match .sh files, and IMO .s files are OK to match as assembly files.

**Comment by jtgans** [comment]
No, weirdly. My files don't have an extension at all, in fact. I wonder if it's the priority, maybe?

**Comment by jtgans** [comment]
For instance, this is on `makedisk` and `make-bootable`. What priority does Nova place on Shell Script? With both extensions disabled, it properly sets up for Shell Script syntax in the editor.

**Comment by jtgans** [comment]
Yeah, the trailing comma would be the likely problem.

**Comment by jtgans** [comment]
Yar! No worries! :D

**Comment by tsalvo** [comment]
I released updates for z80 and 6502 which seem to help. There were a couple of cases where Nova seemed to be remembering which extension had matched a particular file, even if it no longer made sense to match for z80 or 6502 anymore.  But... If I opened the exact same kind of file in a different path, that Nova had never opened before, it matched as Plain Text for me, which seems better now. 

Maybe Nova has some sort of cache for recently opened files and which extensions were used 🤷  but please give the new releases a try and let me know if it's helping in your case. Thanks again for your help in reporting this issue!

**Comment by jtgans** [comment]
Yep, works perfect now. Thanks!
